# Generated by Django 5.1.4 on 2024-12-31 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_photo',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='languafe',
            new_name='language',
        ),
    ]
